name: pl
version: 1.0.2
author: Sisig48
main: fr.sisig48.pl.Main
softdepend: ['Multiverse-Core']
api-version: 1.13
commands:
  mine:
    description: Go to the mine
  spawn:
    description: Go to the spawn
 