location:
  mine:  
    in:
      x: 0.00
      y: 0.00
      z: 0.00
      w: world
    
    out:
      x: 0.00
      y: 0.00
      z: 0.00
      w: world
  
  spawn:
    x: 0.00
    y: 0.00
    z: 0.00
    w: world
