location:
  mine:  
    in:
      x: 0.00
      y: 0.00
      z: 0.00
      w: world
      ya: 0
      pi: 0.0
    
    out:
      x: 0.00
      y: 0.00
      z: 0.00
      w: world
      ya: 0
      pi: 0.0
  
  spawn:
    x: 0.00
    y: 0.00
    z: 0.00
    w: world
    ya: 0
    pi: 0.0
