autoSave: '30'
location:
  spawn:
    x: '0'
    y: '100'
    z: '0'
    w: world
    ya: '0'
    pi: '0'
  mine:
    out:
      x: '0'
      y: '100'
      z: '0'
      w: world
      ya: '0'
      pi: '0'
    in:
      x: '0'
      y: '100'
      z: '0'
      w: world
      ya: '0'
      pi: '0'
    zone:
      w: world
      at:
        x: '0'
        y: '10'
        z: '0'
      to:
        x: '0'
        y: '10'
        z: '0'
      refreshTimeMinute: '30'
  pnj:
    jobs:
      '0': void
    shop:
      '0': void
IntervalePayment: 30
loyerShop: 50
isAhead-Version: 'false'
xp:
  base: '5'
  qtn: '40%'
  min: '0.2'
  max: '7.5'
  line: '8967'
  gain:
    HS: '-70%'
    BAS: '-20%'
    MOYEN: '-5%'
    HAUT: '50%'
    jobs: '50%'
shop:
  marchant:
    sell: '4%'
    buy: '8%'
  shop:
    sell: '8%'
    buy: '10%'
    base: '3%'

