name: ServeurManageur
version: Alpha 1.0.6-friendly
author: Sisig48
main: fr.sisig48.pl.Main
softdepend: ['WorldEdit v7.2.12+6240-87f4ae1', 'Essentials v2.20.0-dev+63-991bc61']
api-version: 1.13
commands:
  mine:
    description: Go to the mine
    usage: /mine
  spawn:
    description: Go to the spawn
    usage: /spawn
  re:
    description: Update plugin ServeurManageur
    permission: admin.command
    usage: /re <get|force|reload|news>
  config:
    description: Config file
    permission: admin.command
    usage: /config [<save|reload>|<get|set> [CONFIG PATH]]
  bug:
    description: Report bug
    permission: admin.command
    usage: /bug [bug...]
  friends:
    description: Manage your friends
    usage: /friends [add|remove|accept] <PLAYER_NAME>
  jobs:
    description: Manage your jobs
    permission: admin.command
    usage: /jobs [add|remove]
  menu:
    description: Open Menu
    usage: /jobs menu
  house:
    description: Spawn House
    permission : admin.command