name: ServeurManageur
version: 1.0.3
author: Sisig48
main: fr.sisig48.pl.Main
softdepend: ['Multiverse-Core']
api-version: 1.13
commands:
  mine:
    description: Go to the mine
  spawn:
    description: Go to the spawn
  re:
    description: Update plugin ServeurManageur
