name: ServeurManageur
version: 1.0.5
author: Sisig48
main: fr.sisig48.pl.Main
softdepend: ['Multiverse-Core']
api-version: 1.13
commands:
  mine:
    description: Go to the mine
    usage: /mine
  spawn:
    description: Go to the spawn
    usage: /spawn
  re:
    description: Update plugin ServeurManageur
    permission: admin.command
    usage: /re <get|force|reload>
  config:
    description: Config file
    permission: admin.command
    usage: /config [<save|reload>|<get|set> [CONFIG PATH]]
  bug:
    description: Report bug
    permission: admin.command
    usage: /bug [bug...]
  